boss:
  display-name: "#ffbb00&lExample Boss"
  entity-type: ZOMBIE
  time-start-period: 5 # in minutes
  damage: 20.0
  boss-bar:
    enable: true
    text: "%beacmcboss_example:display-name%"
    style: SOLID # https://helpch.at/docs/1.16.5/org/bukkit/boss/BarStyle
    color: BLUE # https://helpch.at/docs/1.16.5/org/bukkit/boss/BarColor
  spawn-location:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 67.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  health: 100.0
triggers:
  timer-30-sec:
    type: TIMER
    requirements:
      - '[condition] %beacmcboss_example:time-to-start% == 30'
    actions:
      - '[broadcast] &7Boss %beacmcboss_example:display-name% &7will spawn in 30 seconds'

  timer-10-sec:
    type: TIMER
    requirements:
      - '[condition] %beacmcboss_example:time-to-start% == 10'
    actions:
      - '[broadcast] &7Boss %beacmcboss_example:display-name% &7will spawn in 10 seconds'

  timer-5-sec:
    type: TIMER
    requirements:
      - '[condition] %beacmcboss_example:time-to-start% == 5'
    actions:
      - '[broadcast] &7Boss %beacmcboss_example:display-name% &7will spawn in 5 seconds'


  spawn:
    type: BOSS_SPAWN
    requirements: []
    actions:
      - '[broadcast] &7Boss %beacmcboss_example:display-name%&7 appeared on %beacmcboss_example:loc-world%: %beacmcboss_example:loc-x% %beacmcboss_example:loc-y% %beacmcboss_example:loc-z%'
  death:
    type: BOSS_DEATH
    requirements: []
    actions:
      - '[broadcast] &7Boss %beacmcboss_example:display-name%&7 death'