boss:
  display-name: "#ffbb00&lExample Boss"
  spawn-location:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 67.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  health: 100.0
triggers:
  spawn:
    type: BOSS_SPAWN
    requirements: []
    actions:
      - '[broadcast] Boss {boss-name} appeared on {boss-loc-world}: {boss-loc-x} {boss-loc-y} {boss-loc-z}'
  