settings:

  # use in languages files
  prefix: "#FFE259&lʙ#FFDC58&lᴇ#FFD657&lᴀ#FFD057&lᴄ#FFCA56&lᴍ#FFC555&lᴄ#FFBF54&lʙ#FFB953&lᴏ#FFB353&lꜱ#FFAD52&lꜱ #FFA751&l▸&7"

  # directory: lang
  locale-file: "en.yml"

  # used in TIMER trigger
  #
  # 1 second = 20 ticks
  timer-time: 20

  # used in NEARBY_PLAYERS trigger
  nearby-radius: 10

  # The NEARBY_PLAYERS trigger will execute every 30 seconds.
  nearby-execute-time: 30

# directory: bosses
bosses:

  # boss_name: file.yml
  example: example.yml