name: BeacmcBoss
version: '${project.version}'
main: com.beacmc.beacmcboss.BeacmcBoss
api-version: '1.16'
load: POSTWORLD
depend:
  - PlaceholderAPI
commands:
  boss:
    aliases:
      - bosses
      - beacmcbosses
